modules/BookingService.Orleans/host/EasyAbp.BookingService.Orleans.Web.Host/Controllers/AccountController.cs
using Volo.Abp.AspNetCore.Mvc.Authentication;

namespace EasyAbp.BookingService.Controllers;

public class AccountController : ChallengeAccountController
{

}

modules/BookingService.Orleans/host/EasyAbp.BookingService.Orleans.Web.Host/Pages/Index.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;

namespace EasyAbp.BookingService.Pages;

public class IndexModel : BookingServicePageModel
{
    public void OnGet()
    {

    }

    public async Task OnPostLoginAsync()
    {
        await HttpContext.ChallengeAsync("oidc");
    }
}

modules/BookingService.Orleans/host/EasyAbp.BookingService.Orleans.Web.Host/Pages/Index.cshtml
@page
@using EasyAbp.BookingService.Pages
@model IndexModel
@using Microsoft.AspNetCore.Mvc.Localization
@using EasyAbp.BookingService.Localization
@using Volo.Abp.Users
@inject IHtmlLocalizer<BookingServiceResource> L
@inject ICurrentUser CurrentUser

<abp-card>
    <abp-card-header>Welcome</abp-card-header>
    <abp-card-body>
        @if (!CurrentUser.IsAuthenticated)
        {
            <form method="POST">
                <input type="submit" asp-page-handler="Login" value="LOGIN" class="btn btn-primary" />
            </form>
        }
        else
        {
            <strong>Claims</strong><br />
            @Html.Raw(CurrentUser.GetAllClaims().Select(c => $"{c.Type}={c.Value}").OrderBy(x => x).JoinAsString(" <br /> "))
        }
        <hr />
        <p class="text-end"><a href="https://abp.io?ref=tmpl" target="_blank">abp.io</a></p>
    </abp-card-body>
</abp-card>